package ru.servermine.cities.api;

public enum CityClaimCode {
    CLAIMED, REPLAYED, NOT_FOUND, NOT_MEMBER, PERMISSION_DENIED, PROMOTION_REQUIRED,
    STALE_REVISION, CAP_REACHED, ALREADY_OWNED, TARGET_UNAVAILABLE, PROTECTED_ZONE,
    DISCONNECTED, INSUFFICIENT_FUNDS, INSUFFICIENT_TREASURY, ECONOMY_UNAVAILABLE, OPERATION_CONFLICT,
    OPERATION_IN_PROGRESS, UNKNOWN_OUTCOME, SERVICE_UNAVAILABLE, INTERNAL_ERROR
}
