package ru.servermine.cities.api;

public enum CityMembershipCode {
    INVITED,
    ACCEPTED,
    KICKED,
    NO_CITY,
    PERMISSION_DENIED,
    TARGET_ALREADY_IN_CITY,
    TARGET_NOT_IN_CITY,
    SELF_TARGET,
    CANNOT_KICK_RULER,
    STALE_CITY,
    NOT_INVITED,
    ALREADY_IN_CITY,
    SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
