package ru.servermine.cities.api;

public enum CityPromotionCode {
    PROMOTED,
    REPLAYED,
    NOT_FOUND,
    NOT_MEMBER,
    PERMISSION_DENIED,
    INVALID_STAGE,
    STALE_REVISION,
    REQUIREMENTS_NOT_MET,
    INSUFFICIENT_FUNDS,
    INSUFFICIENT_TREASURY,
    ECONOMY_UNAVAILABLE,
    OPERATION_CONFLICT,
    OPERATION_IN_PROGRESS,
    UNKNOWN_OUTCOME,
    SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
